//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::horse_genders::Entity as HorseGenders;
pub use super::horses::Entity as Horses;
pub use super::notes::Entity as Notes;
pub use super::users::Entity as Users;
